/**
 * Mode role budgets + name→tag seeds (resolved against live catalog by name).
 * Do not treat this as a frozen ID list — IDs come from the API.
 */

/** @type {Record<string, string[]>} */
export const MODE_ROLE_BUDGETS = {
  gemGrab: ['control', 'damage', 'flex'],
  brawlBall: ['tank', 'damage', 'assassin'],
  knockout: ['sniper', 'control', 'flex'],
  hotZone: ['control', 'tank', 'damage'],
  heist: ['damage', 'assassin', 'flex'],
  bounty: ['sniper', 'control', 'flex'],
  wipeout: ['sniper', 'control', 'damage'],
  unknown: ['control', 'damage', 'flex'],
};

/** Tags preferred as safe A1 anchors by mode (research skeletons). */
export const MODE_A1_PREFER = {
  gemGrab: ['control', 'flex', 'tank'],
  brawlBall: ['tank', 'control', 'damage'],
  knockout: ['sniper', 'control', 'flex'],
  hotZone: ['control', 'tank'],
  heist: ['damage', 'flex', 'control'],
  bounty: ['sniper', 'control'],
  wipeout: ['sniper', 'control', 'damage'],
  unknown: ['control', 'flex'],
};

/**
 * Name (lowercase) → archetype tags.
 * Tags: tank, damage, sniper, assassin, control, thrower, support, flex, anti-tank
 */
export const BRAWLER_TAG_SEEDS = {
  shelly: ['flex', 'damage'],
  nita: ['tank', 'control'],
  colt: ['damage', 'sniper', 'anti-tank'],
  bull: ['tank'],
  jessie: ['control', 'damage'],
  brock: ['sniper', 'damage'],
  dynamike: ['thrower', 'damage'],
  bo: ['control', 'sniper'],
  tick: ['thrower', 'control'],
  '8-bit': ['damage', 'anti-tank'],
  emz: ['control', 'damage'],
  'el primo': ['tank'],
  barley: ['thrower', 'control'],
  poco: ['support', 'tank'],
  rosa: ['tank', 'control'],
  rico: ['damage', 'sniper'],
  darryl: ['tank', 'assassin'],
  penny: ['control', 'damage'],
  carl: ['damage', 'tank'],
  jacky: ['tank'],
  stu: ['assassin', 'damage'],
  piper: ['sniper'],
  pam: ['support', 'tank'],
  frank: ['tank'],
  bibi: ['tank', 'assassin'],
  bea: ['sniper', 'control', 'anti-tank'],
  nani: ['sniper', 'damage'],
  edgar: ['assassin'],
  griff: ['damage', 'control', 'anti-tank'],
  grom: ['thrower', 'control'],
  bonnie: ['damage', 'tank'],
  gale: ['control'],
  colette: ['damage', 'anti-tank'],
  belle: ['sniper', 'control', 'anti-tank'],
  ash: ['tank'],
  lola: ['damage'],
  fang: ['assassin'],
  eve: ['control', 'damage'],
  janet: ['damage'],
  otis: ['control'],
  sam: ['tank', 'assassin'],
  gus: ['support'],
  buster: ['tank', 'support'],
  charlie: ['control'],
  mico: ['assassin'],
  berry: ['support', 'control'],
  clancy: ['damage', 'anti-tank'],
  moe: ['tank', 'damage'],
  kenji: ['assassin'],
  mortis: ['assassin'],
  tara: ['control', 'damage'],
  gene: ['control', 'support'],
  max: ['assassin', 'flex'],
  'mr. p': ['control'],
  'mr.p': ['control'],
  'mr p': ['control'],
  sprout: ['thrower', 'control'],
  surge: ['damage', 'assassin'],
  byron: ['support', 'sniper'],
  squeak: ['thrower', 'control'],
  ruffs: ['support', 'control'],
  buzz: ['tank', 'assassin'],
  kit: ['assassin', 'support'],
  larry: ['thrower'],
  lawrie: ['thrower'],
  'larry & lawrie': ['thrower', 'control'],
  angelo: ['sniper'],
  draco: ['tank'],
  lily: ['assassin'],
  shade: ['assassin'],
  meeple: ['flex', 'control'],
  ollie: ['tank', 'control'],
  finx: ['control'],
  lumi: ['damage', 'control'],
  'jae-yong': ['damage', 'flex'],
  kaze: ['assassin'],
  alli: ['assassin'],
  crow: ['assassin', 'control'],
  leon: ['assassin'],
  sandy: ['control', 'support'],
  amber: ['control', 'damage'],
  meg: ['tank', 'damage'],
  spike: ['control', 'damage'],
  lou: ['control'],
  gray: ['support', 'flex'],
  willow: ['control', 'thrower'],
  doug: ['support', 'tank'],
  chuck: ['tank', 'damage'],
  pearl: ['damage', 'control'],
  mandy: ['sniper'],
  chester: ['damage', 'assassin'],
  rt: ['support', 'damage'],
  'r-t': ['support', 'damage'],
  cordelius: ['assassin', 'control'],
  hank: ['tank', 'control'],
  maisie: ['damage', 'anti-tank'],
  melodie: ['assassin', 'damage'],
  juju: ['thrower', 'control'],
  ziggy: ['thrower', 'control'],
  mina: ['assassin'],
  trunk: ['tank'],
};

/** Soft synergy */
export const SYNERGY_TAG_PAIRS = [
  ['tank', 'support'],
  ['tank', 'damage'],
  ['control', 'damage'],
  ['control', 'sniper'],
  ['assassin', 'control'],
  ['thrower', 'tank'],
  ['support', 'damage'],
  ['anti-tank', 'sniper'],
  ['tank', 'assassin'],
];

/**
 * Soft counters (attacker tag → defender tag they beat).
 * Research triangles: tank↔sniper↔anti-tank; assassin↔sniper; control/tank↔assassin.
 */
export const COUNTER_TAG_EDGES = [
  ['tank', 'sniper'],
  ['sniper', 'damage'],
  ['sniper', 'control'],
  ['damage', 'tank'],
  ['anti-tank', 'tank'],
  ['assassin', 'sniper'],
  ['assassin', 'thrower'],
  ['assassin', 'support'],
  ['control', 'assassin'],
  ['tank', 'assassin'],
  ['thrower', 'tank'],
  ['thrower', 'control'],
  ['support', 'tank'],
  ['flex', 'assassin'],
];

export const DRAFT_MODES = [
  { id: 'gemGrab', label: 'Gem Grab' },
  { id: 'brawlBall', label: 'Brawl Ball' },
  { id: 'knockout', label: 'Knockout' },
  { id: 'hotZone', label: 'Hot Zone' },
  { id: 'heist', label: 'Heist' },
  { id: 'bounty', label: 'Bounty' },
  { id: 'wipeout', label: 'Wipeout' },
];
